### ISSUE TITLE
not enough values to unpack (expected 5, got 4)

### ISSUE THREAD

**Issue by Beamhi** [zmwv823/ComfyUI-AnyText#7]
!!! Exception during processing!!! not enough values to unpack (expected 5, got 4)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnyText\AnyText\nodes.py", line 239, in anytext_process
    x_samples, results, rtn_code, rtn_warning, debug_info = pipe(input_data, font_path=loader_out[0], **params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 4)

**Comment by zmwv823** [comment]
- I guess it maybe this situation:

Masks must equal to number of strings_content (in the "") we want to generate.
It's a not an error.
Because i implementation this model in a special way(by reading image from path),  so the masks can't be checked.
Then error raises instead of a reminder.
The code of masks_gen part need rewrite if we want to get this error.
But unfortunatelly i'm not a coder, it need some konwledge of torch、cv2 and pillow functions.
![image](https://github.com/zmwv823/ComfyUI-AnyText/assets/13308350/8990a989-516c-4910-939c-57c46b78c723)
- Official online demo.
![image](https://github.com/zmwv823/ComfyUI-AnyText/assets/13308350/914a9ec5-e2a7-4b5c-9aef-d8b478fbd950)

**Comment by Beamhi** [comment]
thanks! understand it now
